[package]
name = "dioxus-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.1.7", features = ["web", "macro", "hooks", "html"] }
web-sys = { version = "0.3.55", features = ["console"] }
async-std = { version = "1.0" }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.75"
futures = "0.3.19"
async-trait = "0.1.52"
once_cell = "1.9.0"
getrandom = { version = "0.2.4", features = ["js"] }
ws_stream_wasm = "0.7"
reqwest = { version = "0.11.9", features=["json", "multipart", "default-tls"] }
wasm-bindgen-futures = "0.4.29"
