[application]
name = "revolt-client"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "dioxus | ⛺"

[web.watcher]
watch_path = ["src"]
index_on_404 = true

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
