[package]
name = "furor-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.75"
ulid = "0.5.0"
chrono = { version = "0.4" }
